apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    # URL контейнера prometheus внутри Docker-сети
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false