apiVersion: 1

templates:
  - name: telegram.message.v1
    template: |
      {{- $alert := index .Alerts 0 -}}
      {{- if eq $alert.Status "firing" -}}
      🔥 <b>FIRING</b>
      {{- else -}}
      ✅ <b>RESOLVED</b>
      {{- end }}

      <b>Alert:</b> <code>{{ $alert.Labels.alertname }}</code>
      <b>Severity:</b> {{ $alert.Labels.severity | toUpper }}

      {{- /* Получаем «сырое» значение p99 или RPS */ -}}
      {{- $raw := index $alert.Values "B" -}}
      {{- $disp := "N/A" -}}
      {{- if and $raw (ne $raw 0) -}}
        {{- $disp = printf "%.2f" $raw -}}
      {{- end }}

      {{- /* Ветка для HighAPILatency */ -}}
      {{- if eq $alert.Labels.alertname "HighAPILatency" -}}
      <b>Service:</b> API Gateway
      <b>Endpoint:</b> /api/login
      <b>p99 Latency:</b> {{ $disp }}s (threshold: 0.50s)

      {{- /* Ветка для HighDatabaseRPS */ -}}
      {{- else if eq $alert.Labels.alertname "HighDatabaseRPS" -}}
      <b>Service:</b> PostgreSQL
      <b>Metric:</b> commits+rollbacks RPS
      <b>RPS:</b> {{ printf "%.0f" $raw }} (threshold: 100)
      {{- end }}
